Resources:
  TrialSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Test Instance
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: "22"
          ToPort: "22"
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: "8080"
          ToPort: "8080"
          CidrIp: 0.0.0.0/0
  DemoApp:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0022f774911c1d690 
      KeyName: ECSKey
      SecurityGroups:
        - !Ref TrialSG